from app import app, db
from models import Exercise

exercises_data = [
    {"name": "Bridge", "description": "This exercise activates your core and the posterior chain (backside of your body) and is a great warm-up move.", "guide": "Lie on your back with your knees bent, feet flat on the floor, and arms at your sides. Push through your feet and brace your core to raise your bottom until your hips are fully extended, squeezing your glutes at the top. Slowly return to the starting position and repeat."},
    {"name": "Chair Squat", "description": "Bodyweight squats can improve the strength of your muscles, tendons, and bones. Starting with a chair helps you master the proper form.", "guide": "Stand in front of a chair with your feet shoulder-width apart and toes pointed slightly out. Hinge at your hips and bend your knees, lowering your bottom until it touches the chair. Let your arms extend in front of you. Push up through your heels to return to the starting position."},
    {"name": "Knee Pushup", "description": "A beginner-style pushup that helps build upper-body strength before moving on to a standard pushup.", "guide": "Get into a high plank position on your knees. Maintaining a straight line from your head to your knees, bend your elbows at a 45-degree angle to lower yourself to the ground. Push back up to the starting position."},
    {"name": "Stationary Lunge", "description": "This exercise targets your quads, hamstrings, and glutes.", "guide": "Split your stance with your right leg in front and your left foot up on its toes. Bend your knees and lunge until your right thigh is parallel to the ground. Push up through your right foot to return to the starting position. Repeat for the desired number of reps, then switch legs."},
    {"name": "Plank to Downward Dog", "description": "This move tests your upper body, particularly your shoulders.", "guide": "Get into a high plank position with your hands under your shoulders and feet close together. Keep your core engaged, and with your hands and feet stationary, pike your hips up and back into the Downward Dog pose, forming a triangle with the ground. Hold for a second, then return to the plank and repeat."},
    {"name": "Straight-leg Donkey Kick", "description": "A great beginner glute exercise that isolates and contracts the three glute muscles.", "guide": "Get on all fours with your hands under your shoulders and knees under your hips. Keeping your back straight and hips square to the ground, push your right foot out behind you with a straight leg. Squeeze your buttocks at the top and return to the start position. Repeat on the other leg."},
    {"name": "Bird Dog", "description": "A full-body move that requires balance and stability.", "guide": "Get on all fours, ensuring your hands are directly under your shoulders and your knees are under your hips. Keeping your neck neutral, simultaneously extend your left arm and right leg while keeping your hips square to the ground. Pause for 2 seconds, then return to the starting position. Repeat with your right arm and left leg."},
    {"name": "Forearm Plank", "description": "A full-body exercise that can improve overall strength, stability, and athletic performance.", "guide": "Assume a plank position on your forearms, with your body forming a straight line from head to feet. Ensure your lower back and hips do not sag. Hold the position for 30 seconds to 1 minute to complete one set."},
    {"name": "Side-lying Hip Abduction", "description": "Strengthens your hip muscles.", "guide": "Lie on your left side, supporting your head with your left hand and placing your right hand in front of your body. Keeping your legs straight and stacked, lift your right leg up, maintaining your body's position. Return to the start position and repeat for the desired number of reps before switching sides."},
    {"name": "Bicycle Crunch", "description": "This exercise directly targets the rectus abdominis, also known as the \"six pack.\"", "guide": "Lie on your back with your legs in a tabletop position and hands behind your head. Crunch up and bring your right elbow to your left knee, while straightening your right leg. Release the crunch slightly, then bend your right leg and straighten your left leg, bringing your left elbow to your right knee. Repeat for the desired number of reps."},
    {"name": "Standard Pushup", "description": "A classic bodyweight exercise that works the chest, shoulders, and triceps.", "guide": "Start in a high plank position with your hands shoulder-width apart and feet together. Lower your body until your chest nearly touches the floor. Push back up to the starting position."},
    {"name": "Bodyweight Squat", "description": "A fundamental lower-body exercise that strengthens the legs and glutes.", "guide": "Stand with feet shoulder-width apart and toes pointed slightly out. Hinge at your hips and bend your knees, lowering your bottom as if sitting in a chair, keeping your back straight. Push up through your heels to return to the starting position."},
    {"name": "Walking Lunge", "description": "A dynamic lower-body exercise that improves balance and leg strength.", "guide": "Step forward with one leg and lower your hips until both knees are bent at a 90-degree angle. Push off your back foot to bring your body forward into the next lunge. Continue walking forward."},
    {"name": "Mountain Climbers", "description": "A full-body cardiovascular exercise that targets the core.", "guide": "Start in a high plank position. Alternately drive your knees toward your chest as if you are running in place."},
    {"name": "Glute Bridge", "description": "An exercise that activates the glutes and hamstrings.", "guide": "Lie on your back with knees bent, feet flat on the floor, and arms at your sides. Push through your feet to raise your hips until your body forms a straight line from your shoulders to your knees. Squeeze your glutes at the top and hold for a few seconds before lowering."},
    {"name": "Single-leg Deadlift", "description": "A balance-challenging exercise that strengthens the hamstrings, glutes, and core.", "guide": "Stand on one leg. Hinge at your hips and extend your other leg behind you while reaching your hands toward the floor. Return to the starting position and repeat before switching legs."},
    {"name": "Jumping Jacks", "description": "A classic cardiovascular exercise that is a great warm-up.", "guide": "Stand with your feet together and arms at your sides. Jump your feet out to the sides while raising your arms overhead. Jump back to the starting position and repeat."},
    {"name": "High Knees", "description": "A cardio exercise that works the lower body and core.", "guide": "Run in place, driving your knees up toward your chest as high as you can."},
    {"name": "Flutter Kicks", "description": "An exercise that strengthens the lower abs.", "guide": "Lie on your back with your legs extended. Raise your legs a few inches off the floor and perform small, rapid kicking motions. Keep your lower back pressed to the floor."},
    {"name": "Russian Twist", "description": "A core exercise that targets the obliques.", "guide": "Sit on the floor with your knees bent and feet off the ground. Lean back slightly, engaging your core, and twist your torso from side to side."},
    {"name": "Box Jump", "description": "A plyometric exercise that builds explosive leg strength.", "guide": "Stand in front of a sturdy box or bench. Jump onto the box with both feet, landing softly, and then jump back down."},
    {"name": "Handstand Pushup", "description": "An advanced exercise that builds extreme shoulder and upper body strength.", "guide": "Kick up into a handstand against a wall. Lower your body by bending your elbows until your head nearly touches the floor. Push back up to the starting position."},
    {"name": "Pistol Squat", "description": "A challenging single-leg squat that builds lower body strength and balance.", "guide": "Stand on one leg and extend the other leg out in front of you. Lower your body into a deep squat, keeping your balance, and then push back up to the starting position."},
    {"name": "Pull-up", "description": "An advanced upper-body exercise that primarily targets the back and biceps.", "guide": "Hang from a pull-up bar with an overhand grip. Pull your body up until your chin clears the bar. Lower with control."},
    {"name": "Muscle Up", "description": "A highly advanced pulling and pushing exercise that transitions from a pull-up to a dip.", "guide": "Start hanging from a bar. Explosively pull your body up and over the bar, transitioning into a dip to push your torso above the bar. Lower with control."},
    {"name": "Planche Pushup", "description": "A gymnastic-style pushup that builds immense core and upper body strength.", "guide": "Get into a pushup position but with your hands further back and hips elevated. Lean forward, transferring your weight over your hands, and perform a pushup while keeping your body as parallel to the floor as possible."},
    {"name": "Dragon Flag", "description": "An advanced core exercise that builds incredible abdominal strength.", "guide": "Lie on a bench and hold on to the sides. Lift your entire body, from your shoulders to your feet, into a straight line. Lower your body slowly, keeping it straight, until it is just a few inches from the bench. Raise it back up and repeat."},
    {"name": "One-arm Pushup", "description": "A single-arm pushup that requires significant chest and core strength.", "guide": "Get into a pushup position with one hand behind your back. Lower your body until your chest nearly touches the floor, and then push back up using only one arm."},
    {"name": "Commando Pull-up", "description": "A variation of the pull-up that works the biceps and back in a different plane of motion.", "guide": "Grab the bar with a neutral grip (one hand in front of the other). Pull yourself up until your chin is level with the top hand. Lower and switch hand positions for the next rep."},
    {"name": "L-sit", "description": "An advanced core exercise that builds incredible abdominal strength and hip flexor endurance.", "guide": "Sit on the floor with your legs straight out. Place your hands on the floor next to your hips. Press down with your hands to lift your hips and legs off the floor, holding your legs straight out in front of you."}
]

with app.app_context():
    db.drop_all()
    db.create_all()
    for exercise_data in exercises_data:
        exercise = Exercise(**exercise_data)
        db.session.add(exercise)
    db.session.commit()
    print("Database seeded!")